
import { GoogleGenAI, Modality } from "@google/genai";
import { fileToBase64 } from '../utils/fileUtils';

// This check is to prevent crashing in environments where process.env is not defined.
const apiKey = typeof process !== 'undefined' && process.env ? process.env.API_KEY : undefined;
if (!apiKey) {
    throw new Error("API_KEY environment variable is not set.");
}

const ai = new GoogleGenAI({ apiKey });

const PROMPT = `
You are an expert digital artist specializing in creating photorealistic, emotionally resonant composite images.

Your task is to merge the two provided photographs into a single, heartwarming, ultra-realistic image.

The first image is a childhood photo of a person.
The second image is a recent, adult photo of the same person.

Please generate a new image with the following characteristics:

1.  **Concept:** The adult version of the person should be lovingly hugging or interacting with their child version, as if they are meeting in real life for a tender reunion.
2.  **Composition:** Create a natural, believable pose. The interaction should feel authentic and emotionally connected.
3.  **Background:** Completely replace the original backgrounds from both photos with a smooth, softly blurred, neutral background. A very light white or soft pastel color is ideal to create a timeless, clean, and studio-like look.
4.  **Realism & Detail:**
    *   Maintain the distinct facial features and identities from both original photos.
    *   Ensure proportions are realistic for both the child and the adult.
    *   The lighting must be soft, natural, and consistent across both figures, as if they are in the same physical space.
    *   Skin tones must be accurate and rendered with fine, realistic texture.
5.  **Output Quality:** The final image must be of high resolution (4K equivalent or better), with sharp details, and a cinematic depth of field. The overall color balance should be smooth and warm.

Do not include any text, watermarks, or artifacts in the final image. The output should be a single, seamless, photorealistic portrait.
`;

export const generateReunificationImage = async (childPhoto: File, adultPhoto: File): Promise<string> => {
    try {
        const childPhotoBase64 = await fileToBase64(childPhoto);
        const adultPhotoBase64 = await fileToBase64(adultPhoto);

        const childPhotoPart = {
            inlineData: { data: childPhotoBase64, mimeType: childPhoto.type }
        };
        const adultPhotoPart = {
            inlineData: { data: adultPhotoBase64, mimeType: adultPhoto.type }
        };
        const textPart = { text: PROMPT };

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: { parts: [childPhotoPart, adultPhotoPart, textPart] },
            config: {
                responseModalities: [Modality.IMAGE],
            }
        });
        
        if (response.candidates && response.candidates.length > 0) {
            for (const part of response.candidates[0].content.parts) {
                if (part.inlineData) {
                    const base64ImageBytes: string = part.inlineData.data;
                    return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
                }
            }
        }
        
        throw new Error("No image was generated by the model.");

    } catch (error) {
        console.error("Error generating image:", error);
        if (error instanceof Error && error.message.includes('API key not valid')) {
             throw new Error("The API key is invalid. Please check your configuration.");
        }
        throw new Error("Failed to create the image. The model may be unable to process the request. Please try again with different photos.");
    }
};
